### PR TITLE
Extra module complete?

### PR DESCRIPTION
**Pull request by funkybrain**
Hello Steven

Well, that's all I had in mind. Would love some feedback. Too short? Too long? Is the writing style ok? Any typos I missed? Is there anything else I should add?

I'll do a final commit after feedback and remove all the bottom formatting stuff.

Cheers
-Manu

### CODE REVIEW

**Comment by nekopanic** [comment]
At this stage, raw content is more important than formatting and typos. It's a first draft, so expect the whole course to get rewrites for style and consistency.

The content is great! The only thing I would consider is to mention it is _ruby_ specific, as many of the beginners do not ruby experience. But we could also have a repo for them to clone if they want a template.

**Comment by funkybrain** [comment]
I could try and Taylor it to another language? Which one would you
recommend?

**Comment by nekopanic** [comment]
Ruby is perfect! The extras section is for people to explore and have fun. Some beginners are interested in Ruby, and we might even have a few who have completed the Rails Girls beginner course. It's the "default" for Heroku, so it makes sense to do it in Ruby. For lighter stuff there will be a section on using GitHub Pages.

I just think it needs mentioning at the start, so students know the prerequisites for the section.

**Comment by funkybrain** [comment]
Right-o. So, does this mean I should make the changes and send another pull request? and this current pull request will just be cancelled? (yeah, I'm new at this kind of collaborative stuff ^^)

**Comment by nekopanic** [comment]
I've given you direct commit access, so just push everything you like to OpenTechSchool/social-coding 

No pull requests required :)

**Comment by nekopanic** [comment]
@funkybrain, do you want to merge your changes directly? You have access now.

**Comment by funkybrain** [comment]
I will. although i do have a question: does it mean I have to first clone
the whole repo? because if that's the case, i might as well do a pull
request from my fork and then, since you've given me godlike powers, I can
accept the pull request myself... whaddaya think?

**Comment by nekopanic** [comment]
Just go into `.git/config` and change the URL for origin to `git@github.com:OpenTechSchool/social-coding.git`

Then it will consider the OTS repo to be the origin, so push and pull will go straight to OTS.

**Comment by benoitbleuze** [comment]
ahhh some concrete git question here !

you own clone already has a copy of the its repository. you don't need to
clone ur again but simply to add a new remote repository, in addition to
the remote one that is called origin.

look up the command:

git remote add ots git@otsrepo-idont-remember-its-addres.

from now on if you type "git remote show" you will see 2 remote repos :
origin and ots.

you will need to fetch this new repo: "git fetch ots" and you will be able
to see all its branches: "git branch -a" will give you a complete overview.

from then you can play with all the branches and specifically do :

git push ots mySuperDuperBranch:git-pages

which pushes to the its repo your local branch to the ots branch called
git-pages. voilà!

Now you can also use the website to accept the merge. but you won't learn
the wonderful world of multiple remote repository in a single local repo ;-)

Ben

**Comment by benoitbleuze** [comment]
typing long git emails in the metro is harder than i thought.
So excuse the typos I made. Steven's solution leaves your own clone
redondant and useless. If you follow his method, you may as well drop your
own clone. if you prefer to keep your personal  branches separated from the
its official repo, then use multiple remotes.
Ben

**Comment by funkybrain** [comment]
Mmm, I tried to push to ots but I got a 'permission denied (publickey). fatal: The remote end hung up unexpectedly. How do I get the OTS repo to accept my key?

**Comment by nekopanic** [comment]
That's odd. What's the complete error?

**Comment by benoitbleuze** [comment]
Can you push to your own repository right now? From the same machine, using
the same shell?
If yes, check your remote path. Is it https or ssh. And if ssh, is the user
git?

**Comment by funkybrain** [comment]
That's really pretty much it :/

$ git push ots
Enter passphrase for key '/c/Users/Manu/.ssh/id_rsa':
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

I created the ots remote, which added to my .git\config

[remote "ots"]
    url = git@github.com:OpenTechSchool/social-coding.git
    fetch = +refs/heads/_:refs/remotes/ots/_

I fetched and merged the main ots branch to my local (forked) branch to make sure I'm up-to-date and then I just tried bluntly to push everything back to ots after having made a few changes to the heroku module.

I'm getting the sinking sensation that I'm doing this wrong...

edit: I assume my key should be good for any repo on github where I have permission, yes?

**Comment by nekopanic** [comment]
Yes your key is associated with your account, and your account has admin rights to the social-coding repo. Do you see an Admin tab on the [OpenTechSchool/social-coding repo page](https://github.com/OpenTechSchool/social-coding)?

Also, you might like to try the HTTPS alternative, as it won't require an SSH key: `https://github.com/OpenTechSchool/social-coding.git`

**Comment by benoitbleuze** [comment]
Hum. Seems legid. Do you also push using ssh to your repos?
Because you definitely have write access to the social git repo. So things
should be the same for both, as long as you use he same protocols. Stupid
question: are you sure you have typed correctly your passphrase ?

Ben

**Comment by funkybrain** [comment]
OK I went the https alternative ^^

On a side note, what happens if you forget your ssh passphrase... (I don't think I did, but just wondering how deep in it I am if that ever happens).

**Comment by nekopanic** [comment]
Just generate a new one.

**Comment by benoitbleuze** [comment]
You can always add a new key through the web interface, after creating a
new one on your machine.

**Comment by nekopanic** [comment]
forgot to add the required animated gif per-pull request:



there. done.

**Comment by funkybrain** [comment]
he he. btw, what a great learning resource, I'm learning lots of new stuff.

**Comment by benoitbleuze** [comment]
Doing what? Looking for gifs? :-P

**Comment by funkybrain** [comment]
no, I'l learning that when a dev bills me for 6 hrs of work, 5 of those
were probably spent looking for cute animal gifs, and 1 for actually doing
the work he was paid to do :D

**Pull request closed without merging**
